"""initial

Revision ID: 955e9757d6b2
Revises: 
Create Date: 2023-03-26 20:46:11.704757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955e9757d6b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('balance', sa.DECIMAL(precision=21, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=21, scale=2), nullable=True),
    sa.Column('type', sa.Enum('deposit', 'withdraw', name='transactiontype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('user')
    # ### end Alembic commands ###
